create table community_post_likes (
    id int generated by default as identity primary key,
    user_id uuid references auth.users(id) not null,
    community_post_id int references community_posts(id) not null,
    created_at timestamp with time zone default current_timestamp not null
);