create table relapse_dates (
    id int generated by default as identity primary key,
    user_id uuid references auth.users(id) not null,
    date date not null,
    created_at timestamp with time zone default current_timestamp not null
);