create table empty_page (
    id int generated by default as identity primary key,
    user_id uuid references auth.users(id) not null,
    created_at timestamp with time zone default current_timestamp not null,
    updated_at timestamp with time zone default current_timestamp not null,
    title text,
    content text
);

create table ideas (
    id int generated by default as identity primary key,
    content text
);

create table journal_idea (
    id int generated by default as identity primary key,
    created_at timestamp with time zone default current_timestamp not null,
    updated_at timestamp with time zone default current_timestamp not null,
    content text,
    user_id uuid references auth.users(id) not null,
    idea_id int references ideas(id) not null
);

create table mood_check_in (
    id int generated by default as identity primary key,
    user_id uuid references auth.users(id) not null,
    created_at timestamp with time zone default current_timestamp not null,
    updated_at timestamp with time zone default current_timestamp not null,
    mood int,
    note text
);