create table community_posts (
    id int generated by default as identity primary key,
    user_id uuid references auth.users(id) not null,
    created_at timestamp with time zone default current_timestamp not null,
    updated_at timestamp with time zone default current_timestamp not null,
    title text not null,
    content text not null,
    likes int not null default 0,
    replies int not null default 0,
    hashtags text[] not null default '{}'
);

create table community_replies (
    id int generated by default as identity primary key,
    user_id uuid references auth.users(id) not null,
    content text not null,
    created_at timestamp with time zone default current_timestamp not null,
    likes int not null default 0,
    community_post_id int references community_posts(id) not null
);